backend:
  name: git-gateway
local_backend: true
media_folder: static/assets
public_folder: /assets

collections:
  - name: news
    label: News
    label_singular: News Item
    folder: content/news
    create: true
    extension: json
    fields:
      - { name: title, label: Title }
      - { name: summary, label: Summary }
      - { name: content_html, label: Content, widget: markdown }
      - label: "Image"
        name: "image_url"
        widget: "image"
        media_library:
          config:
            multiple: false
      - { name: image_alt, label: Image Alt }
      - { name: date, label: Date Posted, widget: datetime }
  - name: plugins
    label: Plugins
    label_singular: Plugin
    folder: content/plugins
    create: true
    extension: json
    fields:
      - { name: title, label: Title }
      - { name: content_html, label: Content, widget: markdown }
      - label: "Image"
        name: "image_url"
        widget: "image"
        media_library:
          config:
            multiple: false
      - { name: image_alt, label: Image Alt }

  - name: about
    label: About Us
    label_singular: Content
    folder: content/about
    create: true
    extension: json
    fields:
      - { name: title, label: Title }
      - { name: content_html, label: Content, widget: markdown }
      - { name: order, label: Order, widget: number }

  - name: directors
    label: Directors
    label_singular: Director
    folder: content/directors
    create: true
    extension: json
    fields:
      - label: "Image"
        name: "image_url"
        widget: "image"
        media_library:
          config:
            multiple: false
      - { name: title, label: Title }
      - { name: background, label: Background, widget: markdown }
      - { name: order, label: Order, widget: number }
    
  - name: contributors
    label: Contributors
    label_singular: Contributor
    folder: content/contributors
    create: true
    extension: json
    fields:
      
      - label: "Image"
        name: "image_url"
        widget: "image"
        media_library:
          config:
            multiple: false
      - { name: title, label: Name }
      

  - name: developers
    label: Developers Page
    label_singular: Content
    folder: content/developers
    create: false
    extension: json
    fields:
      - { name: title, label: Title }
      - { name: content_html, label: Content, widget: markdown }