backend:
  name: git-gateway
local_backend: true
media_folder: static/assets
public_folder: /assets

collections:
  - name: news
    label: News
    label_singular: News Item
    folder: content/news
    create: true
    extension: json
    fields:
      - { name: title, label: Title }
      - { name: summary, label: Summary }
      - { name: content_html, label: Content, widget: markdown }
      - label: "Image"
        name: "image_url"
        widget: "image"
        media_library:
          config:
            multiple: false
      - { name: image_alt, label: Image Alt }
      - { name: date, label: Date Posted, widget: datetime }
  - name: plugins
    label: Plugins
    label_singular: Plugin
    folder: content/plugins
    create: true
    extension: json
    fields:
      - { name: title, label: Title }
      - { name: content_html, label: Content, widget: markdown }
      - label: "Image"
        name: "image_url"
        widget: "image"
        media_library:
          config:
            multiple: false
      - { name: image_alt, label: Image Alt }
      